<?php
/**
 * save-thumb.php
 * Receives a base64 JPEG thumbnail from the browser (generated by PDF.js),
 * saves it to uploads/library/plate-data/ and updates master_plate_data.image_path.
 */
require_once __DIR__ . '/../../config.php';
require_once __DIR__ . '/../../includes/Db.php';
require_once __DIR__ . '/../../includes/functions.php';

function resolveErpDbName(): string {
    $runtimeFile = realpath(__DIR__ . '/../../../config/db.runtime.php');
    if ($runtimeFile && is_file($runtimeFile)) {
        $runtime = require $runtimeFile;
        if (is_array($runtime)) {
            $host = strtolower((string)($_SERVER['HTTP_HOST'] ?? ''));
            $serverAddr = (string)($_SERVER['SERVER_ADDR'] ?? '');
            $isLocal = ($host === '')
                || (strpos($host, 'localhost') !== false)
                || (strpos($host, '127.0.0.1') !== false)
                || (substr($host, -6) === '.local')
                || ($serverAddr === '127.0.0.1')
                || ($serverAddr === '::1')
                || (bool)preg_match('/^(192\.168\.|10\.|172\.(1[6-9]|2[0-9]|3[01])\.)/', $host)
                || (bool)preg_match('/^(192\.168\.|10\.|172\.(1[6-9]|2[0-9]|3[01])\.)/', $serverAddr);
            $envKey = $isLocal ? 'local' : 'live';
            if (isset($runtime[$envKey]) && is_array($runtime[$envKey])) {
                $dbName = trim((string)($runtime[$envKey]['DB_NAME'] ?? ''));
                if ($dbName !== '') {
                    return $dbName;
                }
            }
        }
    }
    return 'shree_label_erp';
}

header('Content-Type: application/json; charset=utf-8');

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    echo json_encode(['status' => 'error', 'message' => 'Invalid method.']); exit;
}

$user = getAuthUser();
if (!$user) {
    http_response_code(401);
    echo json_encode(['status' => 'error', 'message' => 'Authentication required.']); exit;
}

$fileId      = isset($_POST['file_id'])     ? (int)$_POST['file_id']          : 0;
$plateNumber = isset($_POST['plate_number']) ? trim((string)$_POST['plate_number']) : '';
$imageData   = isset($_POST['image_data'])  ? trim((string)$_POST['image_data'])   : '';

if ($fileId <= 0 || $imageData === '') {
    echo json_encode(['status' => 'error', 'message' => 'Missing parameters.']); exit;
}

// Validate base64 JPEG data URL
if (!preg_match('#^data:image/jpeg;base64,([A-Za-z0-9+/=]+)$#', $imageData, $m)) {
    echo json_encode(['status' => 'error', 'message' => 'Invalid image data.']); exit;
}

$db = Db::getInstance();
$stmt = $db->prepare('SELECT stored_name FROM artwork_final_files WHERE id = ? AND is_active = 1 LIMIT 1');
$stmt->execute([$fileId]);
$row = $stmt->fetch();
if (!$row) {
    echo json_encode(['status' => 'error', 'message' => 'File record not found.']); exit;
}

$storedName = basename((string)$row['stored_name']);
$thumbName  = 'pdf_thumb_' . pathinfo($storedName, PATHINFO_FILENAME) . '.jpg';

// Resolve plate-data directory: 3 levels up from artwork-system/designer/api/ = ERP root
$erpRoot  = (string) realpath(__DIR__ . '/../../..');
$plateDir = $erpRoot . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR . 'library' . DIRECTORY_SEPARATOR . 'plate-data';
if (!is_dir($plateDir)) {
    @mkdir($plateDir, 0755, true);
}

$thumbPath = $plateDir . DIRECTORY_SEPARATOR . $thumbName;

// Decode and save JPEG
$imageBytes = base64_decode($m[1], true);
if ($imageBytes === false || strlen($imageBytes) < 100) {
    echo json_encode(['status' => 'error', 'message' => 'Image decode failed.']); exit;
}

if (file_put_contents($thumbPath, $imageBytes, LOCK_EX) === false) {
    echo json_encode(['status' => 'error', 'message' => 'Cannot write thumbnail file.']); exit;
}

$thumbnailRelPath = 'uploads/library/plate-data/' . $thumbName;
$thumbnailUrl     = ERP_BASE_URL . '/' . $thumbnailRelPath;

// Update master_plate_data.image_path if plate number provided
if ($plateNumber !== '') {
    try {
        $erpConn = new mysqli(ARTWORK_DB_HOST, ARTWORK_DB_USER, ARTWORK_DB_PASS, resolveErpDbName());
        if (!$erpConn->connect_error) {
            $upd = $erpConn->prepare("UPDATE master_plate_data SET image_path = ? WHERE plate = ? LIMIT 1");
            if ($upd) {
                $upd->bind_param('ss', $thumbnailRelPath, $plateNumber);
                $upd->execute();
                $upd->close();
            }
            $erpConn->close();
        }
    } catch (Throwable $e) {
        // Non-fatal
    }
}

echo json_encode(['status' => 'success', 'thumbnail_url' => $thumbnailUrl]);
